<a href="https://colab.research.google.com/github/ArturSiwy/Data-Academy/blob/main/HLTWK3_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1.Create a 1D array of numbers from 0 to 9
#4.Replace all odd numbers in an array of 1-10 with the value 1
import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
#2.Create a 3×3 NumPy array of all Boolean value Trues
import numpy as np
array1 = np.ones((3, 3), dtype=bool)
print(array1)
print(array1.dtype)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
bool


In [37]:
#3.Extract all odd numbers from array of 1-10
array3 = np.arange(1,11)
print(array3)
newarray3 = array3[array3 % 2 == 1]
print(newarray3)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [40]:
#4.Replace all odd numbers in an array of 1-10 with the value 1
array4 = np.arange(1,11)
print(array4)
newarray4 = np.where(array4 % 2 == 1, -1, array4)
print(newarray4)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [42]:
#5.Convert a 1D array to a 2D array with 2 rows
array5 = np.arange(1,11)
print(array5)
newarray5 = array5.reshape(2,5)
print(newarray5)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
#6.Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a = np.arange(0,24,2)
b = np.arange(1,25,2)
print(a)
print(b)
c = np.vstack((a,b))
print(c)
print(np.dot(a, b))
print(np.sum(c,1)) # print sum of each axis (value 1 after coma)
print(np.sum(c,)) # print sum of all axis (no value, default=none)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[ 0  2  4  6  8 10 12 14 16 18 20 22]
 [ 1  3  5  7  9 11 13 15 17 19 21 23]]
2156
[132 144]
276


In [66]:
#Extension1
e = np.ones(3)
print(e)
f = (e+1)
g = (e+2)
print(f)
print(g)
h = np.concatenate((e,f,g))
print(h)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[1. 1. 1. 2. 2. 2. 3. 3. 3.]
